config/routes.rb
Rails.application.routes.draw do
  root 'backups#index'
  resources :backups, only: %i[index create destroy]
  resources :cards, only: %i[index] do
    collection do
      get :search
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/backup.rb
class Backup < ApplicationRecord
  has_many :cards, dependent: :destroy
  after_create :populate_cards

  def self.perform_backup
    uri = URI('https://api.pokemontcg.io/v1/cards?setCode=base4')
    response = Net::HTTP.get(uri)
    response = JSON.parse(response)
    Backup.create(raw_json: response)
  end

  private

  def populate_cards
    json = self.raw_json
    json.values[0].each do |card|
      card['text'] ? text = card['text'].first : text = card['text']
      rarity = Rarity.find_or_create_by!(name: card['rarity'])
      Card.find_or_create_by!(backup: self,
                              rarity: rarity,
                              name: card['name'],
                              image_url: card['imageUrl'],
                              image_url_hires: card['imageUrlHiRes'],
                              description: text,
                              national_pokedex_number: card['nationalPokedexNumber'],
                              evolves_from: card['evolvesFrom'],
                              hp: card['hp'])
    end
  end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :backup
  belongs_to :rarity

  def self.search(backup, params_info)
    if params_info.keys.first.eql?('Rarity')
      rarity = Rarity.find_by(id: params_info.values.first)
      cards = rarity.cards.where(backup: backup)
    else
      col = params_info.keys.first.to_sym
      cards = backup.cards.where("#{col}": params_info.values.first)
    end
    cards
  end
end

app/models/rarity.rb
class Rarity < ApplicationRecord
  has_many :cards
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/backups_controller.rb
class BackupsController < ApplicationController
  before_action :set_backup, only: :destroy
  
  def index
    @last_backup = Backup.last
  end

  def create
    Backup.perform_backup
    redirect_to backups_path, notice: "Backup Created"
  end

  def destroy
    @backup.destroy
    redirect_to backups_path, notice: "Backup Destroyed"
  end
  
  private
  
    def set_backup
      backup_id = params[:id]
      @backup = Backup.find_by(id: backup_id)
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_backup, :set_rarities, :set_hps, :set_names

  def index
    @cards ||= @last_backup.cards
  end

  def search
    parameters = search_params
    @cards = Card.search(@last_backup, parameters)
  end

  private

    def set_backup
      @last_backup = Backup.last
    end

    def set_rarities
      @rarities = Rarity.all
    end

    def set_hps
      @hps = @last_backup.cards.order(:hp).pluck(:hp).uniq.reject{|v| v.nil?}
    end

    def set_names
      @names = @last_backup.cards.order(:name).pluck(:name)
    end

    def search_params
      params.require(:search).permit(:rarity_id, :name, :hp)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backups_helper.rb
module BackupsHelper
end

app/views/backups/index.html.erb
<div class="text-center my-5">
  <%= link_to '<button class="glow-on-hover" type="button"">Create Backup</button>'.html_safe, backups_path, method: :post %> <br /> <br />
  <% if @last_backup.present? %>
    <%= link_to '<button class="glow-on-hover" type="button"">Search</button>'.html_safe, cards_path %> <br /> <br />
    <%= link_to 'Purge Backup', @last_backup, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %> <br />
  <% end %>
</div>

app/views/cards/_cards_list.html.erb
<div class="text-center">
  <% @cards.each do |card| %>
    <%= image_tag card.image_url %>
  <% end %>
</div>

app/views/cards/_search_form.html.erb
<div class="mx-auto my-5 pl-3 pr-3 row">
  <div class="col-4">
    <%= form_for :search, url: search_cards_path, method: :get, class: 'form-inline' do |f| %>
      <div class="form-group">
        <%= f.select(:name, @names , {prompt: "Name..."}, class: 'form-control') %>
        <%= f.submit 'Search', class: 'btn btn-primary form-control' %>
      </div>
    <% end %>
  </div>

  <div class="col-4">
    <%= form_for :search, url: search_cards_path, method: :get do |f| %>
      <div class="form-group">
        <%= f.select(:rarity_id, @rarities.pluck(:name, :id) , {prompt: "Rarity..."}, class: 'form-control')  %>
        <%= f.submit 'Search', class: 'btn btn-primary form-control' %>
      </div>
    <% end %>
  </div>

  <div class="col-4">
    <%= form_for :search, url: search_cards_path, method: :get do |f| %>
      <div class="form-group">
        <%= f.select(:hp, @hps , {prompt: "Hit Point..."}, class: 'form-control')  %>
        <%= f.submit 'Search', class: 'btn btn-primary form-control' %>
      </div>
    <% end %>
  </div>
</div>

app/views/cards/index.html.erb
<%= render 'search_form' %>
<%= render 'cards_list' %>

app/views/cards/search.html.erb
<div class="text-center">
  <%= link_to '<button class="glow-on-hover" type="button"">Clean Search</button>'.html_safe, cards_path %> <br /> <br />
</div>

<%= render 'search_form' %>
<%= render 'cards_list' %>

app/views/layouts/_flash.html.erb
<% flash.each do |key, msg| %>
  <% if key == "notice" %>
    <div class="alert alert-success alert-dismissible fade show col-md-12 text-center">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= msg %>
    </div>
  <% elsif key == "alert_blue" %>
    <div class="alert alert-info alert-dismissible fade show col-md-12 text-center">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= msg %>
    </div>
  <% elsif key == "alert_yellow" %>
    <div class="alert alert-warning alert-dismissible fade show col-md-12 text-center">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= msg %>
    </div>
  <% elsif key == "alert" %>
    <div class="alert alert-danger alert-dismissible fade show col-md-12 text-center">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= msg %>
    </div>
  <% elsif key == "alert_darkblue" %>
    <div class="alert alert-primary alert-dismissible fade show col-md-12 text-center">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= msg %>
    </div>
  <% elsif key == "alert_gray" %>
    <div class="alert alert-secondary alert-dismissible fade show col-md-12 text-center">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= msg %>
    </div>
  <% elsif key == "alert_darkgray" %>
    <div class="alert alert-dark alert-dismissible fade show col-md-12 text-center">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= msg %>
    </div>
  <% elsif key == "alert_light" %>
    <div class="alert alert-light alert-dismissible fade show col-md-12 text-center">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= msg %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokemon Rewind</title>
    <%= favicon_link_tag 'favicon.png' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- CSS only -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= render 'layouts/flash' %>
    <div class="text-center">
      <%= link_to image_tag(asset_path('logo.png'), class: 'logo'), root_path %>
    </div>
    <%= yield %>
  </body>
</html>